# Generated by Django 4.2.3 on 2023-07-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policymodel',
            name='policy_making_process',
        ),
    ]
