# Generated by Django 4.2.3 on 2023-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyApp', '0003_alter_policymodel_cost_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymodel',
            name='policy_choice',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
